// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atdyclyrllwbqptvlpee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0ZHljbHlybGx3YnFwdHZscGVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzk5NTcsImV4cCI6MjA1OTk1NTk1N30.-g4K-4icu5QEOEKynXH39S3Fdm4I7vuyoLf1RpzyVY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create the Supabase client with additional options for better production support
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    storageKey: 'twitch-tts-supabase-auth',
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'implicit'
  },
  global: {
    headers: {
      'x-application-name': 'twitch-tts-reader'
    }
  },
  // Increase timeouts for better reliability in production
  realtime: {
    timeout: 60000 // 60 seconds
  }
});